#ifndef GLOBALES_H
#define GLOBALES_H

#define PRC_ACTIVIDADES 63
#define PRC_EXAMENES 30
#define PRC_TAREAS 7
#define MAX_ASISTENCIAS 34
#define MAX_RETARDOS 3
#define MAX_CALIFICACION 100
#define MIN_CALIFICACION 60
#define MAX_MATERIAS 6
#define MAX_TAREAS 5
#define MAX_RECORDATORIOS 5
#define MAX_NOTAS 10

#endif
